name: install

on: [push, pull_request]

jobs:
  run_script_and_check_python:
    runs-on: ${{ matrix.sys.os }}
    strategy:
      matrix:
        sys:
          - {os: ubuntu-latest, shell: '/bin/zsh'}
          - {os: macos-latest, shell: '/bin/zsh'}
    env:
      SHELL: ${{ matrix.sys.shell }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name:
        run: |
          echo $SHELL

      # - name: Print context
      #   run: printenv
      #
      # - name: Check python version
      #   run: |
      #     python --version
      #
      # - name: Run Shell Script
      #   run: |
      #     ./scripts/bootstrap_mise.sh
      #
      # - name: List mise installed versions
      #   run: |
      #     source ~/.bashrc
      #     mise list

