name: install

on: [push, pull_request]

jobs:
  run_script_and_check_python:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        shell:
          - bash
          # - zsh
    steps:
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: install extra shells
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt install zsh

      - name: whoami
        run: whoami
        shell: 'zsh {0}'

      - name: print shell
        run: |
          echo $SHELL

      - name: set shell
        run: |
          echo SHELL="$(which ${{ matrix.shell }})" >> "$GITHUB_ENV"

      - name: print shell again
        run: |
          echo $SHELL

      - name: Check python version
        run: |
           python --version

      - name: Run Shell Script Bash
        run: |
          ./scripts/bootstrap_mise.sh

      - name: Run Shell Script Bash
        if: ${{ matrix.shell == 'bash' }}
        run: |
          ./scripts/bootstrap_mise.sh
        #shell: bash

      - name: Run Shell Script Zsh
        if: ${{ matrix.shell == 'zsh' }}
        run: |
          ./scripts/bootstrap_mise.sh
        #shell: 'zsh {0}'

      - name: List mise installed versions
        run: |
          source .bashrc
          mise list

