name: install

on: [push, pull_request]

jobs:
  run_script_and_check_python:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        shell:
          - bash
          - zsh
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: print shell
        run: |
          echo $SHELL

      - name: set shell
        run: |
          export SHELL="$(${{ matrix.shell }})"

      - name: print shell again
        run: |
          echo $SHELL

      # - name: Print context
      #   run: printenv
      #
      # - name: Check python version
      #   run: |
      #     python --version
      #
      # - name: Run Shell Script
      #   run: |
      #     ./scripts/bootstrap_mise.sh
      #
      # - name: List mise installed versions
      #   run: |
      #     source ~/.bashrc
      #     mise list

