name: Run Shell Script and Check Python Version

on: [push, pull_request]

jobs:
  run_script_and_check_python:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check python version
        run: |
          python --version

      - name: Run Shell Script
        run: |
          ./scripts/bootstrap_mise.sh

      - name: Reload Shell
        run: |
          exec $SHELL

      - name: List mise installed versions
        run: |
          mise list

